---
title: "SBC for flocker models--data augmented"
author: "Jacob Socolar"
date: "`r Sys.Date()`"
output: html_document
params:
  n_sims: 100
  n_sites: 200
  n_pseudospecies: 100
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup2}
library(flocker)
library(brms)
library(SBC)
set.seed(2)
```


## Data-augmented
```{r data-augmented, eval = FALSE}
# make the stancode
model_name <- paste0(tempdir(), "/sbc_augmented_model.stan")

omega <- rbeta(1, 30, 30)
available <- rbinom(1, params$n_pseudospecies, omega)
unavailable <- params$n_pseudospecies - available
coef_means <- rnorm(5) # normal prior on random effect means
sigma <- abs(rnorm(5)) # half-normal prior on all random effect sds
Sigma <- diag(5) * sigma

fd <- simulate_flocker_data(
  n_pt = params$n_sites, n_sp = available,
  params = list(
    coef_means = coef_means,
    Sigma = Sigma,
    coefs = data.frame(
      det_intercept = rnorm(available, coef_means[1], sigma[1]),
      det_slope_unit = rnorm(available, coef_means[2], sigma[2]),
      det_slope_visit = rnorm(available, coef_means[3], sigma[3]),
      occ_intercept = rnorm(available, coef_means[4], sigma[4]),
      occ_slope_unit = rnorm(available, coef_means[5], sigma[5])
    )
  ),
  seed = NULL,
  rep_constant = FALSE,
  ragged_rep = TRUE
)

obs_aug <- fd$obs[seq_len(params$n_sites), ]

for(i in 2:available){
  obs_aug <- abind::abind(
    obs_aug, 
    fd$obs[((i - 1) * params$n_sites) + seq_len(params$n_sites), ], 
    along = 3
    )
}

event_covs_aug <- list(ec1 = fd$event_covs$ec1[seq_len(params$n_sites), ])
unit_covs_aug <- data.frame(uc1 = fd$unit_covs[seq_len(params$n_sites), "uc1"])

flocker_data = make_flocker_data(
  obs_aug, unit_covs_aug, event_covs_aug,
  type = "augmented", n_aug = unavailable,
  quiet = TRUE)
  
scode <- flocker_stancode(
    f_occ = ~ 0 + Intercept + uc1 + (1 + uc1 || ff_species),
    f_det = ~ 0 + Intercept + uc1 + ec1 + (1 + uc1 + ec1 || ff_species),
    flocker_data = flocker_data,
    prior = 
      brms::set_prior("std_normal()") + 
      brms::set_prior("std_normal()", class = "sd") +
      brms::set_prior("std_normal()", dpar = "occ") +
      brms::set_prior("std_normal()", class = "sd", dpar = "occ") +
      brms::set_prior("beta(30, 30)", dpar = "Omega"),
    backend = "cmdstanr",
    augmented = TRUE
  )
writeLines(scode, model_name)

aug_generator <- function(N){  
  omega <- rbeta(1, 30, 30)
  available <- rbinom(1, params$n_pseudospecies, omega)
  unavailable <- params$n_pseudospecies - available
  coef_means <- rnorm(5) # normal prior on random effect means
  sigma <- abs(rnorm(5)) # half-normal prior on all random effect sds
  Sigma <- diag(5) * sigma
  
  fd <- simulate_flocker_data(
    n_pt = params$n_sites, n_sp = available,
    params = list(
      coef_means = coef_means,
      Sigma = Sigma,
      coefs = data.frame(
        det_intercept = rnorm(available, coef_means[1], sigma[1]),
        det_slope_unit = rnorm(available, coef_means[2], sigma[2]),
        det_slope_visit = rnorm(available, coef_means[3], sigma[3]),
        occ_intercept = rnorm(available, coef_means[4], sigma[4]),
        occ_slope_unit = rnorm(available, coef_means[5], sigma[5])
      )
    ),
    seed = NULL,
    rep_constant = FALSE,
    ragged_rep = TRUE
  )
  
  obs_aug <- fd$obs[seq_len(params$n_sites), ]
  
  for(i in 2:available){
    obs_aug <- abind::abind(
      obs_aug, 
      fd$obs[((i - 1) * params$n_sites) + seq_len(params$n_sites), ], 
      along = 3
      )
  }
  
  event_covs_aug <- list(ec1 = fd$event_covs$ec1[seq_len(params$n_sites), ])
  unit_covs_aug <- data.frame(uc1 = fd$unit_covs[seq_len(params$n_sites), "uc1"])
  
  flocker_data = make_flocker_data(
    obs_aug, unit_covs_aug, event_covs_aug,
    type = "augmented", n_aug = unavailable,
    quiet = TRUE)
  # format for return
  list(
    variables = list(
      `b[1]` = fd$params$coef_means[1],
      `b[2]` = fd$params$coef_means[2],
      `b[3]` = fd$params$coef_means[3],
      `b_occ[1]` = fd$params$coef_means[4],
      `b_occ[2]` = fd$params$coef_means[5],
      `Omega_Intercept` = boot::logit(omega)
    ),
    generated = flocker_standata(
      f_occ = ~ 0 + Intercept + uc1 + (1 + uc1 || ff_species),
      f_det = ~ 0 + Intercept + uc1 + ec1 + (1 + uc1 + ec1 || ff_species),
      flocker_data = flocker_data,
      augmented = TRUE
    )
  )
}

aug_gen <- SBC_generator_function(
  aug_generator, 
  N = params$n_sites
  )
aug_dataset <- suppressMessages(
  generate_datasets(aug_gen, params$n_sims)
)
  
aug_backend <- 
  SBC_backend_cmdstan_sample(
    cmdstanr::cmdstan_model(
      paste0(tempdir(), "/sbc_augmented_model.stan")
      )
    )

aug_results <- compute_SBC(aug_dataset, aug_backend)

plot_ecdf(aug_results)
plot_rank_hist(aug_results)
plot_ecdf_diff(aug_results)

```


